version: "3.8"
services:
  as10_r1:
    image: frrouting/frr
    container_name: as10_r1
    hostname: as10_r1
    restart: always
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    networks:
      - as10-net
    volumes:
      - ./as10_r1/frr:/etc/frr

  
  as10_r2:
    image: frrouting/frr
    container_name: as10_r2
    hostname: as10_r2
    restart: always
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1 
    networks:
      - as10-net
    volumes:
      - ./as10_r2/frr:/etc/frr

  as10_r3:
    image: frrouting/frr
    container_name: as10_r3
    hostname: as10_r3
    restart: always
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    networks:
      - as10-net
    volumes:
      - ./as10_r3/frr:/etc/frr

  as20_r1:
    image: frrouting/frr
    container_name: as20_r1
    hostname: as20_r1
    restart: always
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    networks:
      - as20-net
      - as30-net
      - as10-net
    volumes:
      - ./as20_r1/frr:/etc/frr

  as30_r1:
    image: frrouting/frr
    container_name: as30_r1
    hostname: as30_r1
    restart: always
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    networks:
      - as30-net
      - as10-net
    volumes:
      - ./as30_r1/frr:/etc/frr

  as40_r1:
    image: frrouting/frr
    container_name: as40_r1
    hostname: as40_r1
    restart: always
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    networks:
      - as40-net
      - as20-net
    volumes:
      - ./as40_r1/frr:/etc/frr

  as50_r1:
    image: frrouting/frr
    container_name: as50_r1
    hostname: as50_r1
    restart: always
    privileged: true
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    networks:
      - as50-net
      - as30-net
    volumes:
      - ./as50_r1/frr:/etc/frr

  as10_client:
    image: networkstatic/iperf3
    container_name: as10_client
    hostname: as10_client
    command: -s
    networks:
      - as10-net

  as40_client:
    image: networkstatic/iperf3
    container_name: as40_client
    hostname: as40_client
    command: ["-s"]
    networks:
      - as40-net

  as50_client:
    image: networkstatic/iperf3
    container_name: as50_client
    hostname: as50_client
    command: ["-s"]
    networks:
      - as50-net

volumes:
  frr_vol:

networks:
  as10-net:
  as20-net:
  as30-net:
  as40-net:
  as50-net:
